### ISSUE TITLE
I'm working on a similar curation project and wonder if you're interested in contributing

### ISSUE THREAD

**Issue by tombusby** [decrypto-org/blockchain-papers#10]
https://github.com/tombusby/cypherpunk-research

I'm trying to compile an encyclopedia of ideological/historical/technical sources related to the cypherpunks and their intellectual descendent movements.

Your list of papers is great, very useful to me. I'd like to invite you to contribute to my little history project. If you don't have the time, no problem of course.

**Comment by dionyziz** [comment]
Thanks for the link! I'll take a look at your list and contribute if I have
anything. I'll definitely share it. If you want to copy papers over from my
list, feel free to :)

**Comment by tombusby** [comment]
Thanks a lot man, I'll have a look.
