### ISSUE TITLE
Add celer

### ISSUE THREAD

**Issue by OrfeasLitos** [decrypto-org/blockchain-papers#74]
https://www.celer.network/assets/doc/CelerNetwork-Whitepaper.pdf

DBR payment routing algorithm seems great

**Comment by OrfeasLitos** [comment]
I'll add it after I receive an explanation on a bunch of questions I asked them.

**Comment by dimkarakostas** [comment]
@OrfeasLitos did you receive the explanations? Wanna add it or wait a bit longer?

**Comment by OrfeasLitos** [comment]
I never received any reply and it's been 2.5 months
