### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by itzpc** [decrypto-org/blockchain-papers#88]
Storj A Peer-to-Peer Cloud Storage Network.
Shawn W., Tome B., Josh B.,James P., Gordon H., Patrick G., Philip H., Chris P. '16

2nd paper in Application Category . Link is broken

**Comment by OrfeasLitos** [comment]
Newest version (2018): https://storj.io/storjv3.pdf

BTW, for this type of papers that are unpublished (so we don't have a fixed reference point), should we update the year to the latest version as well?

**Comment by itzpc** [comment]
Its fine. 
Thanks

**Comment by cnasikas** [comment]
> Newest version (2018): https://storj.io/storjv3.pdf
> 
> BTW, for this type of papers that are unpublished (so we don't have a fixed reference point), should we update the year to the latest version as well?

Yes, I think you are right.
